addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  - CXX=g++-4.8
language: node_js
node_js:
  - "6"
script:
  - cross-env BABEL_ENV=test karma start test/unit/karma.config.js --single-run
  - codecov
